apiVersion: 1
datasources:
  - name: Loki
    type: loki
    access: proxy
    url: http://loki-gateway:3100
    jsonData:
      httpHeaderName1: "X-Scope-OrgID"
    secureJsonData:
      httpHeaderValue1: "tenant1"
  - name: prom
    type: prometheus
    access: proxy
    url: http://prom:9090
  - name: tempo
    type: tempo
    access: proxy
    url: http://tempo:3200
